### ISSUE TITLE
Illegal option -o pipefail

### ISSUE THREAD

**Issue by hongbo-miao** [bartdorlandt/ansible-role-poetry#1]
I am setting up Ubuntu 22.04 by

```yaml
- name: Install packages
  hosts: hm-ubuntu
  roles:
    - role: staticdev.pyenv
      pyenv_version: v2.3.23
      pyenv_env: user
      pyenv_python_versions:
        - 3.11.4
      pyenv_global:
        - 3.11.4
    - role: bartdorlandt.poetry
      vars:
        virtualenvs_inproject: false
        virtualenvs_prefer_active_python: false
```

And got error

```shell
TASK [bartdorlandt.poetry : Install Poetry] ************************************
fatal: [hm-ubuntu]: FAILED! => {"changed": true, "cmd": "set -o pipefail && curl -sSL https://install.python-poetry.org | python3 -", "delta": "0:00:00.002447", "end": "2023-08-03 16:18:11.426375", "msg": "non-zero return code", "rc": 2, "start": "2023-08-03 16:18:11.423928", "stderr": "/bin/sh: 1: set: Illegal option -o pipefail", "stderr_lines": ["/bin/sh: 1: set: Illegal option -o pipefail"], "stdout": "", "stdout_lines": []}
```

However, I can run `set -o pipefail && curl -sSL https://install.python-poetry.org | python3 -` directly in this Ubuntu:

```shell
set -o pipefail && curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/parallels/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.5.1): Creating environment
# ...
```

Any ideas? Thanks! ☺️
