### ISSUE TITLE
Matching Poetry parameter default values

### ISSUE THREAD

**Issue by hongbo-miao** [bartdorlandt/ansible-role-poetry#2]
Currently I saw in readme, it has two parameters which are set to true`, however, the default values in Poetry are different.

Just a suggestion, it would be great to match Poetry parameter default values. So that people won't be surprised when not pass any parameters by default. Thanks! 😃

- `virtualenvs_inproject: true` -> `virtualenvs.in-project: null`: https://python-poetry.org/docs/configuration/#virtualenvsin-project
- `virtualenvs_prefer_active_python: true` -> `virtualenvs.prefer-active-python: false` (experimental): https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental

**Comment by bartdorlandt** [comment]
Feel free to do a PR 😉👍

**Comment by hongbo-miao** [comment]
Hi @bartdorlandt I tried to contribute, however as I am still new to Ansible. I am not sure how to handle below situation correctly. Need some help from you, thanks! ☺️

Here is what I found:

`virtualenvs.in-project` can have three values `null`, `true`, `false`, and by default is `null`.

(Note `null` is what I got from `poetry config virtualenvs.in-project`, while the [official document](https://python-poetry.org/docs/configuration/#virtualenvsin-project) is using `None`)

So actually based on current code

https://github.com/bartdorlandt/ansible-role-poetry/blob/163188619d6a12d327c795655bb622e26aac8bcd/tasks/main.yml#L18-L26

1. When pass `virtualenvs_inproject: false` in this role, it actually preserve default `null` instead of setting to `false`:

    ```shell
    parallels@ubuntu-linux-22-04-desktop:~/.local/bin$ poetry config virtualenvs.in-project
    null
    ```

2. When pass `virtualenvs_inproject: true` in this role, it will set to `true`.
3. Currently, there is no way to set to `false`.

I was hoping to change to default `null`, so updated code would be like

```yaml
 - name: Check Poetry virtualenvs.in-project config 
   ansible.builtin.command: poetry config virtualenvs.in-project 
   register: poetry_in_project 
   changed_when: ??? # not sure here 
   when: virtualenvs_inproject 
  
 - name: Configure Poetry virtualenvs.in-project 
   ansible.builtin.command: poetry config virtualenvs.in-project {{ virtualenvs_inproject }}  # not sure if I did correct
   when: virtualenvs_inproject != poetry_in_project.stdout
```

However, I have two questions inside. Sorry still too new to Ansible...
